[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = espota
upload_port = kawai-klavier.local
monitor_port = COM10
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
lib_deps =
    https://github.com/sauloverissimo/ESP32_Host_MIDI.git
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7
    fastled/FastLED@^3.6
